server:
  port: 9001

kafka:
  bootstrap-address: localhost:29092
  group-id: api-gateway-group
  topics: {
    purchase-product: purchase-product,
    product-bought: product-bought,
    not-available-products-found: not-available-products-found
  }

services:
  order-service: http://localhost:9002
  products-catalogue-service: http://localhost:9003

spring:
  jackson:
    serialization:
      indent_output: true