server:
  port: 9001

kafka:
  bootstrap-address: localhost:29092
  group-id: api-gateway-group
  topics: {
    purchase-product: purchase-product,
    product-bought: product-bought,
    product-not-bought: product-not-bought
  }

services:
  order-service: http://localhost:9002
  products-catalogue-service: http://localhost:9003
  accounting-service: http://localhost:9004
  transport-service: http://localhost:9005
  notification-service: http://localhost:9006

spring:
  jackson:
    serialization:
      indent_output: true