### list of all products
GET http://localhost:9001/product

### list of all orders
GET http://localhost:9001/order

### details of the order where {orderId} is an identifier of the order
GET http://localhost:9001/order/orderId

### list of all invoices
GET http://localhost:9001/invoice

### list of all transport orders
GET http://localhost:9001/transport-order

### list of all notifications
GET http://localhost:9001/notification

### list of all purchases
GET http://localhost:9001/purchase

### details of the purchase where {purchaseId} is an identifier of the order
GET http://localhost:9001/purchase/purchaseId

### allows to purchase products
POST http://localhost:9001/purchase
Content-Type: application/json

{
  "buyerId": 13,
  "products": [4, 5],
  "street": "Grodzka 13",
  "postalCode": "01-234",
  "city": "Cracow"
}
