server:
  port: 9002

kafka:
  bootstrap-address: localhost:29092
  group-id: order-service-group
  topics: {
    purchase-product: purchase-product,
    product-bought: product-bought,
    product-not-bought: product-not-bought
  }

services:
  products-catalogue-service: http://localhost:9003

spring:
  jackson:
    serialization:
      indent_output: true